### ISSUE TITLE
Option to retrieve only opened issues

### ISSUE THREAD

**Issue by laurentj** [jreinhardt/handkerchief#20]
For my purpose, having access to closed issue is useless. And then it is useless to download hundred issues where only few issues are opened.
 
In fact, it may be the default behavior..

**Comment by jreinhardt** [comment]
I added a commandline switch, but left the defaults as they are.

**Comment by laurentj** [comment]
Thank you :-)

**Comment by dwainm** [comment]
Thanks for this @jreinhardt  !

**Comment by dwainm** [comment]
@jreinhardt when running 
handkerchief --state open woothemes/sensei

It simply return this:

```
usage: Download GitHub Issues into self-contained HTML file
       [-h] [-o OUTNAME] [-l LAYOUT] [-q VERBOSE] [--state {all,open,closed}]
       [--local] [-a] [--no-local-avatars]
       [reponame [reponame ...]]

```

Is there something wrong with my command ?

**Comment by jreinhardt** [comment]
Hmm, that is strange, works here as expected.

Can you give some details about your OS, python version? Does it work without the state switch?

**Comment by dwainm** [comment]
@jreinhardt I'm running OSX Yosimite.

After trying it on an ubuntu server this worked nicely:

python handkerchief.py woothemes/sensei --state open

**Comment by jreinhardt** [comment]
So this works on OSX as well or on ubuntu only?

**Comment by dwainm** [comment]
I can't confirm OSX yet as I'm getting this : 

```
$ handkerchief woothemes/sensei --state open
There is a problem with the request
https://api.github.com/repos/jreinhardt/handkerchief/contents/layouts/default/default.json
<Response [403]>
```

I pressed Ctrl-C ( CMD-C ) to quit the script while it was in operation and got the above when retrying. I need to restart the system and test it again.

**On ubutnu:**

handkerchief --state open woothemes/sensei

Returns this:

````
usage: Download GitHub Issues into self-contained HTML file
       [-h] [-o OUTNAME] [-l LAYOUT] [-q VERBOSE] [--state {all,open,closed}]
       [--local] [-a] [--no-local-avatars]
       [reponame [reponame ...]]
````

But this works on ubuntu : 
python handkerchief.py woothemes/sensei --state open

**Comment by jreinhardt** [comment]
For unauthenticated API calls GitHub poses a rate limit of 50 or 60 requests per hour. This usually is not a problem, but when testing or debugging handkerchief, you hit this pretty quickly. In this case on gets an error message just like you got. So it might be that it just works again after a while.

Alternatively you can use the -a switch to authenticate your api calls.

**Comment by jreinhardt** [comment]
I just realized that you probably use the bash function that is described in the README. I never tested this (someone else suggested it for use on MacOS), and it indeed seems buggy.

Can you try to remove the whole function from your .bashrc file and replace it with

   alias fftr='python path/to/handkerchief.py'

If this works for you on MacOS, I will update the readme accordingly.
