### ISSUE TITLE
page title shows html

### ISSUE THREAD

**Issue by philfreo** [jreinhardt/handkerchief#22]
minor bug

![screenshot 2015-04-22 15 24 33](https://cloud.githubusercontent.com/assets/97612/7286824/b2c3dec8-e903-11e4-8c64-7f1c3e145619.png)

**Comment by jreinhardt** [comment]
I can not reproduce this behaviour here (Firefox), but I added a title tag with useful content to the default theme, so your browser should not need to guess a title.
