### ISSUE TITLE
add option to resize avatars

### ISSUE THREAD

**Issue by aaronpk** [jreinhardt/handkerchief#32]
First of all, thanks for this, this is a great project!

I tried this on a semi-active repo of mine, and it resulted in a 3.7mb HTML file including avatars. Without the avatars it was 0.7mb. Since the avatars are always displayed as 50x50, it would be great if they could be resized when downloading them, in order to reduce the size of the resulting HTML.

GitHub has a query string parameter that can do the resizing itself, e.g. https://avatars0.githubusercontent.com/u/113001?s=100 so that might be an easy way to go about this.

**Comment by jreinhardt** [comment]
Thanks for the hint. This made it extremely easy.
